import SVG = require("./Resources/IbizaSvgs");

"use strict";

export const Icons = {
    activityIcon: SVG.Content.Images.activity,
    activityScriptIcon: SVG.Content.Images.activityScript,
    adlStore: SVG.Content.Images.adlStore,
    azureDbTable: SVG.Content.Images.azureDBTable,
    blobTable: SVG.Content.Images.blobTable,
    dataFactoryIcon: SVG.Content.Images.aDF,
    diagramIcon: SVG.Content.Images.diagram,
    loading: SVG.Content.Images.ellipsisSquare,
    linkedService: SVG.Content.Images.linkedService,
    tableIcon: SVG.Content.Images.table,
    tableSchemaIcon: SVG.Content.Images.tableSchema,
    sqlDwTable: SVG.Content.Images.sqlDwTable,
    sqlTable: SVG.Content.Images.sqlTable,
    dataPipelineIcon: SVG.Content.Images.pipeline,
    dataSliceIcon: SVG.Content.Images.slice,
    activityRunIcon: SVG.Content.Images.job,
    graphPipelineIcon: SVG.Content.Images.graphPipeline,
    graphActivityIcon: SVG.Content.Images.graphActivity,
    zoomOneHundredPercentIcon: SVG.Content.Images.FloorplanToolbar.zoomOneHundredPercent,
    zoomInIcon: SVG.Content.Images.FloorplanToolbar.zoomIn,
    zoomOutIcon: SVG.Content.Images.FloorplanToolbar.zoomOut,
    zoomToFitIcon: SVG.Content.Images.FloorplanToolbar.zoomToFit,
    lockIcon: SVG.Content.Images.FloorplanToolbar.lock,
    selectionModeIcon: SVG.Content.Images.FloorplanToolbar.selectionMode,
    lineageDisplayIcon: SVG.Content.Images.FloorplanToolbar.lineageDisplay,
    autolayoutIcon: SVG.Content.Images.FloorplanToolbar.autolayout,
    resumePipelineIcon: SVG.Content.Images.ActionToolbar.resume,
    cancelPipelineIcon: SVG.Content.Images.ActionToolbar.stop,
    pausePipelineIcon: SVG.Content.Images.ActionToolbar.pause,
    dropdownIcon: SVG.Content.Images.ActionToolbar.dropdown,
    rerunDropdownIcon: SVG.Content.Images.ActionToolbar.rerunDropdown,
    // TODO iannight: needs new icon
    rerunSlicesIcon: SVG.Content.Images.ActionToolbar.rerunSlices,
    inProgressIcon: SVG.Content.Images.StatusIcons.inProgress,
    retryIcon: SVG.Content.Images.StatusIcons.retry,
    viewSourceIcon: SVG.Content.Images.viewSource,
    pipelineSourceIcon: SVG.Content.Images.pipelineSource,
    book: SVG.Content.Images.book,
    quickstart: SVG.Content.Images.quickstart,
    tools: SVG.Content.Images.tools,
    onPremisesHDFS: SVG.Content.Images.onPremisesHDFS,
    sampleIcon: SVG.Content.Images.SampleDeployment.sample,
    sampleCustomerProfilingIcon: SVG.Content.Images.SampleDeployment.customerProfilingSample,
    sampleCustomerChurnIcon: SVG.Content.Images.SampleDeployment.customerChurnSample,
    sampleProductRecommendationIcon: SVG.Content.Images.SampleDeployment.productRecommendationSample,
    suggestSampleIcon: SVG.Content.Images.SampleDeployment.suggestSample
};
