//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.DataStudio.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataStudioResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataStudioResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.DataStudio.Services.DataStudioResources", typeof(DataStudioResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rules are valid..
        /// </summary>
        internal static string AllRulesAreValid {
            get {
                return ResourceManager.GetString("AllRulesAreValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule is valid..
        /// </summary>
        internal static string RuleIsValidError {
            get {
                return ResourceManager.GetString("RuleIsValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proposed value &quot;{0}&quot; could not be parsed as a boolean..
        /// </summary>
        internal static string ValueCannotBeParsedAsBoolean {
            get {
                return ResourceManager.GetString("ValueCannotBeParsedAsBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proposed value &quot;{0}&quot; could not be parsed as a double precision floating point..
        /// </summary>
        internal static string ValueCannotBeParsedAsDouble {
            get {
                return ResourceManager.GetString("ValueCannotBeParsedAsDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proposed value &quot;{0}&quot; could not be parsed as an integer..
        /// </summary>
        internal static string ValueCannotBeParsedAsInt {
            get {
                return ResourceManager.GetString("ValueCannotBeParsedAsInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proposed value &quot;{0}&quot; is greater than the maximum value of &quot;{1}&quot;..
        /// </summary>
        internal static string ValueIsGreaterThanMax {
            get {
                return ResourceManager.GetString("ValueIsGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proposed value &quot;{0}&quot; is less than the minimum value of &quot;{1}&quot;..
        /// </summary>
        internal static string ValueIsLessThanMin {
            get {
                return ResourceManager.GetString("ValueIsLessThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proposed value &quot;{0}&quot; is not one of the allowed enum values [{1}] of the parameter..
        /// </summary>
        internal static string ValueIsNotInEnumValues {
            get {
                return ResourceManager.GetString("ValueIsNotInEnumValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a valid boolean value..
        /// </summary>
        internal static string ValueMustBeBoolean {
            get {
                return ResourceManager.GetString("ValueMustBeBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be one of the following values: {0}..
        /// </summary>
        internal static string ValueMustBeEnumValues {
            get {
                return ResourceManager.GetString("ValueMustBeEnumValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a float between &quot;{0}&quot; and &quot;{1}&quot; inclusive..
        /// </summary>
        internal static string ValueMustBeFloat {
            get {
                return ResourceManager.GetString("ValueMustBeFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be an int between &quot;{0}&quot; and &quot;{1}&quot; inclusive..
        /// </summary>
        internal static string ValueMustBeInt {
            get {
                return ResourceManager.GetString("ValueMustBeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “{0}” must have at least one value。.
        /// </summary>
        internal static string ValuesMustHaveAtLeastOneValue {
            get {
                return ResourceManager.GetString("ValuesMustHaveAtLeastOneValue", resourceCulture);
            }
        }
    }
}
